using Dapper;
using ApiOracle.Data;
using ApiOracle.Models;

namespace ApiOracle.Repositories
{
    public class ClienteRepository
    {
        private readonly OracleConnectionFactory _factory;

        public ClienteRepository(OracleConnectionFactory factory)
        {
            _factory = factory;
        }

        public async Task CriarTabelaAsync()
        {
            using var conn = _factory.CreateConnection();

            var sql = @"
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE CLIENTES (
                        ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        NOME VARCHAR2(100),
                        EMAIL VARCHAR2(100)
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
            ";

            await conn.ExecuteAsync(sql);
        }

        public async Task<int> InserirAsync(Cliente cliente)
        {
            using var conn = _factory.CreateConnection();

            var sql = @"
                INSERT INTO CLIENTES (NOME, EMAIL)
                VALUES (:Nome, :Email)
                RETURNING ID INTO :Id";

            var parameters = new DynamicParameters();
            parameters.Add("Nome", cliente.Nome);
            parameters.Add("Email", cliente.Email);
            parameters.Add("Id", dbType: System.Data.DbType.Int32, direction: System.Data.ParameterDirection.Output);

            await conn.ExecuteAsync(sql, parameters);

            return parameters.Get<int>("Id");
        }

        public async Task<IEnumerable<Cliente>> ListarAsync()
        {
            using var conn = _factory.CreateConnection();

            var sql = "SELECT ID, NOME, EMAIL FROM CLIENTES";

            return await conn.QueryAsync<Cliente>(sql);
        }
    }
}