using Dapper;
using ApiOracle.Data;
using ApiOracle.Models;

namespace ApiOracle.Repositories
{
    public class InspecaoRepository
    {
        private readonly OracleConnectionFactory _factory;

        public InspecaoRepository(OracleConnectionFactory factory)
        {
            _factory = factory;
        }

        public async Task CriarTabelaAsync()
        {
            using var conn = _factory.CreateConnection();

            var sql = @"
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE INSPECOES (
                        ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        TITLE VARCHAR2(200),
                        LOCATION VARCHAR2(200),
                        ADDRESS VARCHAR2(400),
                        NOTES VARCHAR2(4000),
                        Q1 VARCHAR2(200),
                        Q2 VARCHAR2(200),
                        Q3 VARCHAR2(200),
                        Q4 VARCHAR2(200),
                        Q5 VARCHAR2(200),
                        Q6 VARCHAR2(200),
                        CREATED_AT DATE NOT NULL,
                        USUARIO_ID NUMBER NOT NULL
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
            ";

            await conn.ExecuteAsync(sql);
        }

        public async Task<int> InserirAsync(Inspecao inspecao)
        {
            using var conn = _factory.CreateConnection();

            var sql = @"
                INSERT INTO INSPECOES (TITLE, LOCATION, ADDRESS, NOTES, Q1, Q2, Q3, Q4, Q5, Q6, CREATED_AT, USUARIO_ID)
                VALUES (:Title, :Location, :Address, :Notes, :Q1, :Q2, :Q3, :Q4, :Q5, :Q6, :CreatedAt, :UsuarioId)
                RETURNING ID INTO :Id";

            var parameters = new DynamicParameters();
            parameters.Add("Title", inspecao.Title);
            parameters.Add("Location", inspecao.Location);
            parameters.Add("Address", inspecao.Address);
            parameters.Add("Notes", inspecao.Notes);
            parameters.Add("Q1", inspecao.Q1);
            parameters.Add("Q2", inspecao.Q2);
            parameters.Add("Q3", inspecao.Q3);
            parameters.Add("Q4", inspecao.Q4);
            parameters.Add("Q5", inspecao.Q5);
            parameters.Add("Q6", inspecao.Q6);
            parameters.Add("CreatedAt", inspecao.CreatedAt);
            parameters.Add("UsuarioId", inspecao.UsuarioId);
            parameters.Add("Id", dbType: System.Data.DbType.Int32, direction: System.Data.ParameterDirection.Output);

            await conn.ExecuteAsync(sql, parameters);

            return parameters.Get<int>("Id");
        }

        public async Task AtualizarAsync(Inspecao inspecao)
        {
            using var conn = _factory.CreateConnection();

            var sql = @"
                UPDATE INSPECOES SET
                    TITLE = :Title,
                    LOCATION = :Location,
                    ADDRESS = :Address,
                    NOTES = :Notes,
                    Q1 = :Q1,
                    Q2 = :Q2,
                    Q3 = :Q3,
                    Q4 = :Q4,
                    Q5 = :Q5,
                    Q6 = :Q6
                WHERE ID = :Id";

            await conn.ExecuteAsync(sql, inspecao);
        }

        public async Task<Inspecao?> GetByIdAsync(int id)
        {
            using var conn = _factory.CreateConnection();

            var sql = @"SELECT ID, TITLE, LOCATION, ADDRESS, NOTES, Q1, Q2, Q3, Q4, Q5, Q6, CREATED_AT AS CreatedAt, USUARIO_ID AS UsuarioId FROM INSPECOES WHERE ID = :Id";

            return await conn.QueryFirstOrDefaultAsync<Inspecao>(sql, new { Id = id });
        }

        public async Task<IEnumerable<Inspecao>> ListarAsync()
        {
            using var conn = _factory.CreateConnection();

            var sql = @"SELECT ID, TITLE, LOCATION, ADDRESS, NOTES, Q1, Q2, Q3, Q4, Q5, Q6, CREATED_AT AS CreatedAt, USUARIO_ID AS UsuarioId FROM INSPECOES";

            return await conn.QueryAsync<Inspecao>(sql);
        }

        public async Task<IEnumerable<Inspecao>> ListarPorUsuarioAsync(int usuarioId)
        {
            using var conn = _factory.CreateConnection();

            var sql = @"SELECT ID, TITLE, LOCATION, ADDRESS, NOTES, Q1, Q2, Q3, Q4, Q5, Q6, CREATED_AT AS CreatedAt, USUARIO_ID AS UsuarioId FROM INSPECOES WHERE USUARIO_ID = :UsuarioId";

            return await conn.QueryAsync<Inspecao>(sql, new { UsuarioId = usuarioId });
        }

        public async Task DeleteAsync(int id)
        {
            using var conn = _factory.CreateConnection();

            var sql = @"DELETE FROM INSPECOES WHERE ID = :Id";

            await conn.ExecuteAsync(sql, new { Id = id });
        }
    }
}
