using Dapper;
using ApiOracle.Data;
using ApiOracle.Models;

namespace ApiOracle.Repositories
{
    public class UsuarioRepository
    {
        private readonly OracleConnectionFactory _factory;

        public UsuarioRepository(OracleConnectionFactory factory)
        {
            _factory = factory;
        }

        public async Task CriarTabelaAsync()
        {
            using var conn = _factory.CreateConnection();

            var sql = @"
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE USUARIOS (
                        ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        NOME_COMPLETO VARCHAR2(200),
                        EMAIL VARCHAR2(200),
                        DATA_NASCIMENTO DATE,
                        PASSWORD_HASH VARCHAR2(4000),
                        IS_ADMIN NUMBER(1) DEFAULT 0
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
            ";

            await conn.ExecuteAsync(sql);
        }

        public async Task<int> InserirAsync(Usuario usuario)
        {
            using var conn = _factory.CreateConnection();

            var sql = @"
                INSERT INTO USUARIOS (NOME_COMPLETO, EMAIL, DATA_NASCIMENTO, PASSWORD_HASH, IS_ADMIN)
                VALUES (:NomeCompleto, :Email, :DataNascimento, :PasswordHash, :IsAdmin)
                RETURNING ID INTO :Id";

            var parameters = new DynamicParameters();
            parameters.Add("NomeCompleto", usuario.NomeCompleto);
            parameters.Add("Email", usuario.Email);
            parameters.Add("DataNascimento", usuario.DataNascimento);
            parameters.Add("PasswordHash", usuario.PasswordHash);
            parameters.Add("IsAdmin", usuario.IsAdmin ? 1 : 0);
            parameters.Add("Id", dbType: System.Data.DbType.Int32, direction: System.Data.ParameterDirection.Output);

            await conn.ExecuteAsync(sql, parameters);

            return parameters.Get<int>("Id");
        }

        public async Task<Usuario?> GetByEmailAsync(string email)
        {
            using var conn = _factory.CreateConnection();

            var sql = "SELECT ID, NOME_COMPLETO AS NomeCompleto, EMAIL, DATA_NASCIMENTO AS DataNascimento, PASSWORD_HASH AS PasswordHash, IS_ADMIN AS IsAdmin FROM USUARIOS WHERE EMAIL = :Email";

            return await conn.QueryFirstOrDefaultAsync<Usuario>(sql, new { Email = email });
        }

        public async Task<Usuario?> GetByIdAsync(int id)
        {
            using var conn = _factory.CreateConnection();

            var sql = "SELECT ID, NOME_COMPLETO AS NomeCompleto, EMAIL, DATA_NASCIMENTO AS DataNascimento, PASSWORD_HASH AS PasswordHash, IS_ADMIN AS IsAdmin FROM USUARIOS WHERE ID = :Id";

            return await conn.QueryFirstOrDefaultAsync<Usuario>(sql, new { Id = id });
        }

        public async Task<IEnumerable<Usuario>> ListarAsync()
        {
            using var conn = _factory.CreateConnection();

            var sql = "SELECT ID, NOME_COMPLETO AS NomeCompleto, EMAIL, DATA_NASCIMENTO AS DataNascimento, IS_ADMIN AS IsAdmin FROM USUARIOS";

            return await conn.QueryAsync<Usuario>(sql);
        }
    }
}
