namespace ApiOracle.Models
{
    public class PtEfluenteCreateDto
    {
        public string? PkCdMeioAmbienteCptm { get; set; }
        public string? TxNrElementoMonitoramento { get; set; }
        public string? TxNmElementoMonitoramento { get; set; }
        public string? TxSiglaDeptoMeioAmbiente { get; set; }
        public string? TxStatusDoDesvioAmbiental { get; set; }
        public string? TxStatusDoRegistroNoBd { get; set; }
        public string? TxMunicipio { get; set; }
        public string? TxLinhaCptm { get; set; }
        public string? TxViaCptm { get; set; }
        public string? TxTrechoESentidoCptm { get; set; }
        public string? TxKmPoste { get; set; }
        public string? TxEstacaoCptm { get; set; }
        public decimal? NrLatGrauDecimalWgs84 { get; set; }
        public decimal? NrLongGrauDecimalWgs84 { get; set; }
        public decimal? NrLatMetrosSirgas2000 { get; set; }
        public decimal? NrLongMetrosSirgas2000 { get; set; }
        public string? TxNmLocalEscopoContratual { get; set; }
        public string? TxTipoDeFormulario { get; set; }
        public DateTime? DtDataEmissaoFormulario { get; set; }
        public int? NrNumeroDeFormulario { get; set; }
        public string? TxAutorPfDoFormulario { get; set; }
        public string? TxNaturezaDoPga { get; set; }
        public string? TxNomePjExecutora { get; set; }
        public string? TxTipoAtividadeListada { get; set; }
        public string? TxTipoAtividadeNListada { get; set; }
        public string? TxTipoDraListado { get; set; }
        public string? TxTipoDraNListado { get; set; }
        public string? TxIdDra { get; set; }
        public DateTime? DtValidadeDra { get; set; }
        public string? TxAnaliseCptmAprovacao { get; set; }
        public string? TxTipoAtividadeCptm { get; set; }
        public string? TxNmLocalAtiv { get; set; }
        public string? TxNmLocalAtivComplemento { get; set; }
        public string? TxOrigemEfluente { get; set; }
        public string? TxFonteGeradora { get; set; }
        public decimal? NrQuantidadeL { get; set; }
        public string? TxTipoDestinacao { get; set; }
        public string? TxTipoVeiculo { get; set; }
        public string? TxIdVeiculo { get; set; }
        public string? TxIdGuiaRemessa { get; set; }
        public decimal? NrDistanciaDaViaM { get; set; }
        public string? TxOfereceRiscoSistemaCptm { get; set; }
        public string? TxProprietario { get; set; }
        public string? TxObsCadastramento { get; set; }
        public DateTime? DtDataDoCadastramento { get; set; }
        public string? HrHoraDoCadastramento { get; set; }
        public string? TxAutorPjDoCadastro { get; set; }
        public string? TxAutorPfDoCadastro { get; set; }
        public string? TxNmResponsavelCadastro { get; set; }
        public string? TxRpResponsavelCadastro { get; set; }
        public string? TxDrtResponsavelCadastro { get; set; }
        public string? TxNomePjDaContratada { get; set; }
        public string? TxNrContratoContratada { get; set; }
        public string? TxNmAreaGestoraCptm { get; set; }
        public string? TxIdAreaGestoraCptm { get; set; }
        public string? TxSiglaAreaGestoraCptm { get; set; }
        public string? TxNomePfDaRepresentante { get; set; }
        public string? TxNomePjDaSupervisora { get; set; }
        public string? TxNrContratoSupervisora { get; set; }
        public string? TxNmArquivoFdcRelacionado { get; set; }
        public string? PkCdArquivoFdcRelacionado { get; set; }
        public string? TxNmArquivoRvtRelacionado { get; set; }
        public string? PkCdElementoDeMonitorRvt { get; set; }
        public string? TxNmArquivoDacRelacionado { get; set; }
        public string? PkCdElementoDeMonitorDac { get; set; }
        public string? TxNmArquivoCncRelacionado { get; set; }
        public string? PkCdElementoDeMonitorCnc { get; set; }
        public string? PkCdCodigoNoUltimoRra { get; set; }
        public string? PkCdCedoc { get; set; }
        public string? TxNomeFoto01 { get; set; }
        public string? TxNomeFoto02 { get; set; }
        public string? TxNomeFoto03 { get; set; }
        public string? TxNomeFoto04 { get; set; }
    }
}
